[tool.poetry]
name = "bang"
version = "0.1.0"
description = ""
authors = ["bhyun08 <nbhyun0329@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
